version: '3'
services:
  postgres:
    image: postgres
    restart: always 
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
    
    

  app:
    build:
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "80:8080"

    env_file:
    - .env
    depends_on:
      - postgres

    
  pgadmin:
    image: dpage/pgadmin4:6.12
    ports:
      - "5080:80"
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    volumes:
      - ./db-data/pgadmin/:/home/rundeck/server/data

    